#  Feature Scalling

In [3]:
pip install -U scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
df=pd.read_csv('Churn_Modelling.csv')

In [9]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [19]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [21]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [23]:
df.describe().round(2)

RowNumber   CustomerId  CreditScore       Age    Tenure    Balance  \
count   10000.00     10000.00     10000.00  10000.00  10000.00   10000.00   
mean     5000.50  15690940.57       650.53     38.92      5.01   76485.89   
std      2886.90     71936.19        96.65     10.49      2.89   62397.41   
min         1.00  15565701.00       350.00     18.00      0.00       0.00   
25%      2500.75  15628528.25       584.00     32.00      3.00       0.00   
50%      5000.50  15690738.00       652.00     37.00      5.00   97198.54   
75%      7500.25  15753233.75       718.00     44.00      7.00  127644.24   
max     10000.00  15815690.00       850.00     92.00     10.00  250898.09   

       NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary   Exited  
count       10000.00   10000.00        10000.00         10000.00  10000.0  
mean            1.53       0.71            0.52        100090.24      0.2  
std             0.58       0.46            0.50         57510.49      0.4  
min             1.00       0.00            0.00            11.58      0.0  
25%             1.00       0.00            0.00         51002.11      0.0  
50%             1.00       1.00            1.00        100193.92      0.0  
75%             2.00       1.00            1.00        149388.25      0.0  
max             4.00       1.00            1.00        199992.48      1.0

In [25]:
 df.head(5)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [27]:
new_df=pd.DataFrame(df,columns = ['Age','Tenure'])

In [29]:
new_df.head()

Age  Tenure
0   42       2
1   41       1
2   42       8
3   39       1
4   43       2

In [35]:
new_df['Age']=new_df['Age'].fillna(new_df['Age'].mean())

In [39]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     10000 non-null  int64
 1   Tenure  10000 non-null  int64
 2   age     10000 non-null  int64
dtypes: int64(3)
memory usage: 234.5 KB


In [43]:
scaler= MinMaxScaler() # Instantiating the MinMaxScaler() function
normalized_df=scaler.fit_transform(new_df)
print(normalized_df)

[[0.32432432 0.2        0.32432432]
 [0.31081081 0.1        0.31081081]
 [0.32432432 0.8        0.32432432]
 ...
 [0.24324324 0.7        0.24324324]
 [0.32432432 0.3        0.32432432]
 [0.13513514 0.4        0.13513514]]


 # Let's  take another small example

In [48]:
x_array = np.array([[2],[3],[5],[6],[6]])

scaler=MinMaxScaler()
normalized_arr = scaler.fit_transform(x_array)
print(normalized_arr)

[[0.  ]
 [0.25]
 [0.75]
 [1.  ]
 [1.  ]]


# STANDARDIZATION

In [57]:
scaler = StandardScaler()
standardized_df=scaler.fit_transform(new_df)
print(standardized_df)

[[ 0.29351742 -1.04175968  0.29351742]
 [ 0.19816383 -1.38753759  0.19816383]
 [ 0.29351742  1.03290776  0.29351742]
 ...
 [-0.27860412  0.68712986 -0.27860412]
 [ 0.29351742 -0.69598177  0.29351742]
 [-1.04143285 -0.35020386 -1.04143285]]


In [61]:
x_array = np.array([[2],[3],[5],[6],[6]])
scaler = StandardScaler()
normalized_arr_ss = scaler.fit_transform(x_array)
print(normalized_arr_ss)

[[-1.47709789]
 [-0.86164044]
 [ 0.36927447]
 [ 0.98473193]
 [ 0.98473193]]
